### ISSUE TITLE
osync.remote.$SCRIPT_PID.$TSTAMP folders are not deleted

### ISSUE THREAD

**Issue by victor-vc** [deajan/osync#226]
I noticed on the target machine there is a lot of "osync.remote.$SCRIPT_PID.$TSTAMP" folders in the /tmp folder. Those folders are created each time osync runs on the initiator machine. Shouldn't those temporary folders be deleted by the script? Also, the logs don't show any errors.

**Comment by deajan** [comment]
Hello,

Guess you're using osync v1.2. This has been corrected for ages in current master.
I really need to make a release, the v1.3-RC is way more stable than anything previous ;)

**Comment by victor-vc** [comment]
Hello,

I am using osync for several months now but the issue with the temporary folders not being deleted only came up a week ago or so (based on the oldest timestamp).

According to the logs, my osync version is 1.3.0-rc1. Here are the first lines of the log file:

> TIME: 0 - Cannot get value for [VERSION] in config file [/etc/os-release].
TIME: 0 - -------------------------------------------------------------
TIME: 0 - Sun Mar 21 23:45:01 EET 2021 - osync 1.3.0-rc1 script begin.
TIME: 0 - -------------------------------------------------------------
TIME: 0 - Sync task [xxxxxxxxx] launched as yyyyyyyyy (PID 2304138)
TIME: 1 - Starting synchronization task.

**Comment by victor-vc** [comment]
It is also worth mentioning that I am using osyn-batch.sh, and I have noticed that my osync-batch.sh script has way more lines than the current git master version (2257 lines vs. 355 lines), although the script versions are the same "PROGRAM_BUILD=2020031502".

**Comment by deajan** [comment]
Yes, there was a build error in osync-batch.sh that put too much (unused) code Into it.
Would you mind updating to latest git master please?

**Comment by victor-vc** [comment]
I have just tried with the latest git master. The issue is still present, the temporary folders are not deleted from /tmp on the target machine. In addition, I got a notification warning by email: "TIME: 0 - (WARN):This is an unstable dev build [2020111501]. Please use with caution.". I managed to get rid of the warning message by setting IS_STABLE to "true". 

On the initiator machine all the temp folders (created in /tmp) are deleted. Only on the target machine the clean up doesn't work.

As a temporary solution I added **REMOTE_RUN_AFTER_CMD="rm -rf /tmp/osync.remote.*"** to the conf file.

However, what intrigues me most is that the issue occurred just two weeks ago.

**Comment by deajan** [comment]
Done in current builds
